/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import proyecto3algoritmos.Grafo;
import proyecto3algoritmos.Nodo;

/**
 *
 * @author Alejandro
 */
public class AgregarArista extends javax.swing.JInternalFrame implements ActionListener{

    private JComboBox comboOrigen;
    private JComboBox comboDestino;
    
    private Grafo grafo;
    
    /**
     * Creates new form AgregarArista
     */
    public AgregarArista(Grafo grafo) {
        super("Agregar Arista");
        this.grafo=grafo;
        initComponents();
        iniciar();
    }// constructor

    private void iniciar(){
        Nodo temp=this.grafo.getNodoInicial();
        Object[] vector=new Object[this.grafo.size()];
        int i=0;
        while(temp!=null){
            vector[i]=temp.getId();
            temp=temp.getSiguienteNodo();
            i++;
        }
        comboOrigen=new JComboBox(vector);
        comboOrigen.setBounds(100, 10, 100, 30);
        comboOrigen.addActionListener(this);
        this.add(comboOrigen);
        
        cargarComboDestino();
    }// iniciar
    
    private void cargarComboDestino(){
        Nodo temp=this.grafo.getNodoInicial();
        Object[] vector;
        if(this.grafo.size()>0)
            vector=new Object[this.grafo.size()-1];
        else vector=new Object[0];
        int i=0;
        while(temp!=null){
            if(comboOrigen.getSelectedItem().equals(temp.getId())!=true){
                vector[i]=temp.getId();
                i++;
            }
            temp=temp.getSiguienteNodo();
        }
        comboDestino=new JComboBox(vector);
        comboDestino.setBounds(100, 50, 100, 30);
        this.add(comboDestino);
    }// cargarComboDestino
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setClosable(true);

        jLabel1.setText("Destino:");

        jLabel2.setText("Origen:");

        jButton1.setText("Agregar Arista");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Peso:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3)
                        .addGap(48, 48, 48)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        char origen=(char)comboOrigen.getSelectedItem();
        char destino=(char)comboDestino.getSelectedItem();
        int peso=Integer.parseInt(jTextField1.getText());
        this.grafo.agregarAristaNodo(origen, destino, peso);
        this.grafo.agregarAristaNodo(destino, origen, peso);
        VentanaPrincipal.panel.setGrafo(grafo);
        this.setVisible(false);
        this.grafo.imprimirGrafo();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==comboOrigen){
            this.remove(comboDestino);
            cargarComboDestino();
            repaint();
        }
    }
    
}// AgregarArista
